### ISSUE TITLE
Incorrect vault rewards in 10.1

### ISSUE THREAD

**Issue by Sythr4l** [Lardeck/PermoksAccountManager#8]
Hello!

Love this addon.  I noticed the mouseover for M+ vault is showing incorrect ilvls.

![image](https://github.com/Lardeck/PermoksAccountManager/assets/113131440/47759b1b-4494-4d1b-af61-48ab9cdd1ca2)

Below is from the vault:
![image](https://github.com/Lardeck/PermoksAccountManager/assets/113131440/e5cd01b8-25e6-4b94-b898-fe3a79b7fed6)

**Comment by Lardeck** [comment]
Thx! Forgot about that. Will update tomorrow!
